{% set version = "0.1.6" %}
{% set url_base = "https://github.com/lab-cosmo/metatensor/releases/download" %}

package:
  name: metatensor
  version: {{ version }}

source:
  url: {{ url_base }}/metatensor-core-v{{ version }}/metatensor-core-cxx-{{ version }}.tar.gz
  sha256: 13e5e6554589e0c9e201768a50a6b51dffc882f0b60cdf2ad4335b7c2045d87c
  patches:
    - mktemp-mkdir.patch

build:
  number: 0


requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cmake
    - ninja
    - cargo-bundle-licenses
  run:

test:
  commands:
    - test -f $PREFIX/lib/libmetatensor$SHLIB_EXT  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\metatensor.dll exit 1  # [win]

about:
  home: https://github.com/lab-cosmo/metatensor
  summary: 'Self-describing sparse tensor data format for atomistic machine learning and beyond'
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml
  doc_url: https://lab-cosmo.github.io/metatensor/

extra:
  recipe-maintainers:
    - Luthaf
    - PicoCentauri
