package:
  name: metatensor
  version: 0.2

build:
  number: 1
  noarch: generic

requirements:
  run:
    - libmetatensor
    - python-metatensor-core
    - python-metatensor-operations
    - python-metatensor-learn

test:
  commands:
    # check if libmetatensor files exists
    - test -f $PREFIX/lib/libmetatensor$SHLIB_EXT  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\metatensor.dll exit 1  # [win]

about:
  home: https://github.com/metatensor/metatensor
  summary: 'Self-describing sparse tensor data format for atomistic machine learning and beyond'
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
  doc_url: https://docs.metatensor.org/

extra:
  recipe-maintainers:
    - Luthaf
    - PicoCentauri
