package:
  name: metatensor
  version: 0.2

build:
  number: 0
  noarch: generic

requirements:
  run:
    - libmetatensor
    - libmetatensor-torch

test:
  commands:
    # check if libmetatensor files exists
    - test -f $PREFIX/lib/libmetatensor$SHLIB_EXT  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\metatensor.dll exit 1  # [win]
    # check if libmetatensor-torch files exists
    - test -f $PREFIX/lib/libmetatensor_torch$SHLIB_EXT  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\metatensor_torch.dll exit 1  # [win]

about:
  home: https://github.com/lab-cosmo/metatensor
  summary: 'Self-describing sparse tensor data format for atomistic machine learning and beyond'
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
  doc_url: https://lab-cosmo.github.io/metatensor/

extra:
  recipe-maintainers:
    - Luthaf
    - PicoCentauri
