{% set version = "0.1.5" %}
{% set url_base = "https://github.com/lab-cosmo/metatensor/releases/download" %}

package:
  name: metatensor
  version: {{ version }}

source:
  url: {{ url_base }}/metatensor-core-v{{ version }}/metatensor-core-cxx-{{ version }}.tar.gz
  sha256: 8ecac73604d79d7f3e46880cd14370d85b26ade3c9aa8ab9594678e8f3083a4f
  patches:
    - mktemp-mkdir.patch

build:
  number: 0


requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cmake
    - ninja
    - cargo-bundle-licenses
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - test -f $PREFIX/lib/libmetatensor$SHLIB_EXT  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\metatensor.dll exit 1  # [win]

about:
  home: https://github.com/lab-cosmo/metatensor
  summary: 'Self-describing sparse tensor data format for atomistic machine learning and beyond'
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml
  doc_url: https://lab-cosmo.github.io/metatensor/

extra:
  recipe-maintainers:
    - Luthaf
    - PicoCentauri
